import { EcuInfo } from '../types';

export const KNOWN_ECU_NODES: Omit<EcuInfo, 'status' | 'dtcCount' | 'supportedPidsCount'>[] = [
  {
    id: 'ecu-engine',
    nameEn: 'Engine Control Module (ECM / PCM)',
    nameAr: 'وحدة التحكم في المحرك (ECM / PCM)',
    addressHex: '0x7E0',
    txIdHex: '0x7E0',
    rxIdHex: '0x7E8',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-trans',
    nameEn: 'Transmission Control Module (TCM)',
    nameAr: 'وحدة التحكم في ناقل الحركة (TCM)',
    addressHex: '0x7E1',
    txIdHex: '0x7E1',
    rxIdHex: '0x7E9',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-abs',
    nameEn: 'Anti-lock Braking & VSC Module (ABS/ESP)',
    nameAr: 'نظام الفرامل والثبات الإلكتروني (ABS / VSC)',
    addressHex: '0x7E2',
    txIdHex: '0x7E2',
    rxIdHex: '0x7EA',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-airbag',
    nameEn: 'Supplemental Restraint System (Airbag / SRS)',
    nameAr: 'وحدة الوسائد الهوائية ونظام الأمان (Airbag / SRS)',
    addressHex: '0x7E3',
    txIdHex: '0x7E3',
    rxIdHex: '0x7EB',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-bcm',
    nameEn: 'Body Control Module (Main Body / BCM)',
    nameAr: 'كمبيوتر الهيكل والأنظمة المركزية (BCM)',
    addressHex: '0x7E4',
    txIdHex: '0x7E4',
    rxIdHex: '0x7EC',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-cluster',
    nameEn: 'Combination Meter (Instrument Cluster)',
    nameAr: 'لوحة العدادات وشاشة السائق (Instrument Cluster)',
    addressHex: '0x7E5',
    txIdHex: '0x7E5',
    rxIdHex: '0x7ED',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-hvac',
    nameEn: 'Air Conditioning & Climate Control (HVAC)',
    nameAr: 'وحدة التحكم في التكييف والمناخ (HVAC)',
    addressHex: '0x7E6',
    txIdHex: '0x7E6',
    rxIdHex: '0x7EE',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-tpms',
    nameEn: 'Tire Pressure Monitor System (TPMS)',
    nameAr: 'نظام مراقبة ضغط الإطارات (TPMS)',
    addressHex: '0x7E7',
    txIdHex: '0x7E7',
    rxIdHex: '0x7EF',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  },
  {
    id: 'ecu-eps',
    nameEn: 'Electric Power Steering (EPS / EMPS)',
    nameAr: 'وحدة التوجيه الكهربائي المعزز (EPS)',
    addressHex: '0x720',
    txIdHex: '0x720',
    rxIdHex: '0x728',
    protocol: 'ISO 15765-4 CAN 11-bit 500k',
    softwareVersion: '',
    hardwareVersion: '',
    partNumber: '',
  }
];

export class EcuScanner {
  public static getStandardEcuList(): EcuInfo[] {
    return KNOWN_ECU_NODES.map(node => ({
      ...node,
      status: 'OFFLINE',
      dtcCount: 0,
      supportedPidsCount: 0
    }));
  }
}
